### ISSUE TITLE
mongodb deployment is created even when disabled

### ISSUE THREAD

**Issue by slyt** [shalb/charts#6]
A mongodb deployment and associated pod is created even when the following are set in values.yaml:

```yaml
chat:
  enabled: false

mongodb:
  install: false
```
