### ISSUE TITLE
Make `HUGGINGFACE_OFFLINE` configurable

### ISSUE THREAD

**Issue by slyt** [shalb/charts#7]
Currently [HUGGINGFACE_OFFLINE=1](https://github.com/shalb/charts/blob/7c29f2185336ed8d9cb14ffae9942f6b95462d12/huggingface-model/templates/application.yaml#L101-L102) is hardcoded in the helm template.

I'd like for it to be configurable in values.yaml so that I don't have to pull models from s3 and can download them directly from huggingface hub via the functionality in huggingface text-generation-inference image.

**Comment by slyt** [comment]
I was able to overwrite it with:

```yaml
extraEnvVars:
  - name: HUGGINGFACE_OFFLINE
    value: "0"
```
